sudo: false
language: go

go:
  - 1.9.7
  - 1.11.2
  - tip

os:
  - linux
  - osx

env:
  - GO111MODULE=on

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

script:
  - go test -v -race ./...
