version: '{build}'
clone_folder: C:\gopath\src\github.com\xiegeo\thuder
environment:
  GOPATH: C:\gopath
build_script:
- cmd: >-
    go version

    go env

    go get -v -t github.com/xiegeo/thuder/...

    go build github.com/xiegeo/thuder
test_script:
- cmd: go test -v github.com/xiegeo/thuder
