version: '{build}'
clone_folder: C:\gopath\src\github.com\xiegeo\thuder
environment:
  GOPATH: C:\gopath
stack: 
  - go 1.10 386
  - go 1.11 amd64
for:
  - matrix:
      only:
        - stack: go 1.10 386
    environment:
      GOARCH: 386
      GOROOT: C:\go110
      PATH: C:\go110;%PATH%
    test_script:
      - cmd: go test -v github.com/xiegeo/thuder
  - matrix:
      only:
        - stack: go 1.11 amd64
    environment:
      GOARCH: amd64
      GOROOT: C:\go111
      GO111MODULE: on
    test_script:
      - cmd: go test -v -race github.com/xiegeo/thuder
build_script:
- cmd: |-
    go version
    go env
    go get -v -t github.com/xiegeo/thuder/...
    go build github.com/xiegeo/thuder
    go build github.com/xiegeo/thuder/thuder
