version: '{build}'
clone_folder: C:\gopath\src\github.com\xiegeo\thuder
environment:
  GOPATH: C:\gopath
  GO111MODULE: on
stack: 
  - go 1.10
  - go 1.11
for:
  - matrix:
      only:
        - stack: go 1.10
    environment:
      GOARCH: 386
    test_script:
      - cmd: go test -v github.com/xiegeo/thuder
  - matrix:
      only:
        - stack: go 1.11
    install:
      - rd c:\go /s /q
      - appveyor DownloadFile https://dl.google.com/go/go1.11.windows-amd64.zip
      - 7z x go1.11.windows-amd64.zip -oC:\ >nul
    test_script:
      - cmd: go test -v -race github.com/xiegeo/thuder
build_script:
- cmd: >-
    go version

    go env

    go get -v -t github.com/xiegeo/thuder/...

    go build github.com/xiegeo/thuder
	
    go build github.com/xiegeo/thuder/thuder

